In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

np.int64(8)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
new_arry = arr[0:6]
new_arry

array([0, 1, 2, 3, 4, 5])

In [11]:
new_arry[:] = 99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_copy[0:6] = 100
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

索引二維陣列（矩陣）
一般格式是 arr_2d[row][col] 或 arr_2d[row, col]。我推薦使用逗號標記法以增加清晰度。

In [16]:
import numpy as np
arr_2d = np.array([[5,10,15],
                   [50,25,30],
                    [35,40,45]  ])
arr_2d

array([[ 5, 10, 15],
       [50, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1]

array([50, 25, 30])

In [18]:
arr_2d[1][2]

np.int64(30)

In [19]:
arr_2d[1,2]

np.int64(30)

In [20]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

條件選擇
這是一個非常基礎的概念，稍後將直接應用於 pandas，請確保你理解這部分！

我們來簡要介紹如何使用括號進行基於比較運算符的選擇。

In [21]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [23]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

算術運算
你可以輕鬆地進行陣列與陣列的算術運算，或者標量與陣列的算術運算。讓我們來看一些例子：

In [25]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [28]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
arr / arr

C:\Users\s4292\AppData\Local\Temp\ipykernel_22456\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [30]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

通用陣列函數
NumPy 提供了許多[通用陣列函數](https://numpy.org/doc/stable/reference/ufuncs.html)，或稱為 ufuncs（universal functions），它們本質上是可以應用於整個陣列的數學運算。讓我們來展示一些常見的通用函數：

np.add - 對陣列中的元素進行加法運算。
np.subtract - 對陣列中的元素進行減法運算。
np.multiply - 對陣列中的元素進行乘法運算。
np.divide - 對陣列中的元素進行除法運算。
np.sqrt - 計算陣列中每個元素的平方根。
np.exp - 計算 e 的指數，應用於陣列中的每個元素。
np.log - 計算陣列中每個元素的自然對數。
np.sin, np.cos, np.tan - 分別計算陣列中元素的正弦、餘弦和正切值。
這些函數可以對整個陣列進行快速和有效的元素級運算，使得數據處理更加方便和高效。

In [31]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [33]:
np.log(arr) #e

C:\Users\s4292\AppData\Local\Temp\ipykernel_22456\3818696041.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #e


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

陣列的摘要統計
NumPy 也提供了常見的摘要統計功能，如 sum（總和）、mean（平均值）和 max（最大值）。你可以將這些函數作為陣列的方法來調用。下面是如何使用這些統計方法的例子：

np.sum(arr) - 計算陣列 arr 中所有元素的總和。
np.mean(arr) - 計算陣列 arr 中所有元素的平均值。
np.max(arr) - 找出陣列 arr 中的最大元素。
np.min(arr) - 找出陣列 arr 中的最小元素。
np.std(arr) - 計算陣列 arr 中元素的標準差。
np.var(arr) - 計算陣列 arr 中元素的方差。
這些摘要統計函數能幫助你快速獲得數據的整體統計特徵，對於數據分析和處理非常有用。

In [34]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr.sum()

np.int64(45)

In [36]:
arr.mean()

np.float64(4.5)

In [37]:
arr.var()

np.float64(8.25)

軸邏輯
在處理二維陣列（矩陣）時，我們必須考慮行和列。當我們進入到 pandas 的相關部分時，這會變得非常重要。在陣列中，軸 0（零）代表垂直軸（行），而軸 1 則是水平軸（列）。這些值（0,1）對應於 arr.shape 返回值的順序。

讓我們看看這如何影響我們上面提到的摘要統計計算：

當使用軸 0 進行操作時，意味著沿著行（垂直方向）進行計算，將每一列的值聚合起來。例如，計算每一列的總和或平均值。
當使用軸 1 進行操作時，則沿著列（水平方向）進行計算，將每一行的值聚合起來。例如，計算每一行的總和或平均值。
這種區分在進行統計分析時非常重要，它確保你可以按照期望的方向對數據進行操作。這種對軸的理解同樣適用於更高維度的數據處理。讓我們看一個例子，如果有一個矩陣 arr 如下所示：

[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
使用 np.sum(arr, axis=0) 將返回每一列的總和：[12, 15, 18]
使用 np.sum(arr, axis=1) 將返回每一行的總和：[6, 15, 24]
這樣的操作讓我們可以根據具體需求選擇適當的軸進行數據統計。

In [38]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
arr = arr.reshape(3,4)

In [40]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr.sum(axis=0)

array([15, 18, 21, 24])

In [42]:
arr.sum(axis=1)

array([10, 26, 42])

In [43]:
arr.sum()

np.int64(78)

NumPy 練習

In [44]:
import numpy as np

2. 創建一個包含10個零的陣列

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. 創建一個包含10個1的陣列  
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [47]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

4. 產生10個5的陣列
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. 創建一個包含從10到50的整數的陣列
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [49]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. 要創建一個包含從10到50的所有偶數整數的陣列

In [50]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. 要創建一個3x3矩陣，其中包含從0到8的值
```array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. 要創建一個3x3的單位矩陣（identity matrix）
```array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

要使用 NumPy 生成一個介於0和1之間的隨機數

In [53]:
np.random.rand(1)

array([0.02013593])

要使用 NumPy 生成一個包含25個從標準正態分布（平均值為0，標準差為1的正態分布）抽樣的隨機數陣列


In [54]:
np.random.randn(25)

array([ 0.38073649, -0.11719498, -1.80277062,  0.01624146,  1.27150424,
       -0.29526961,  0.8029844 , -1.74773245,  0.30535739, -0.09865255,
       -0.09039455,  1.03067462, -0.16133222, -0.22045437,  1.58253407,
        0.65502664, -1.32671392,  0.36151534, -1.64982434,  0.9095106 ,
        0.72941451,  1.5646672 ,  0.39065206, -2.12454378,  0.69083951])

要創建一個包含從0到1之間20個等距點的陣列
```array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [55]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Numpy Indexing and Selection
幫我產生以下的陣列

```array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

根據以下輸出完成功能
```array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [58]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

輸出如下
array([[ 2],
       [ 7],
       [12]])

In [59]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

根據以下輸出完成功能
array([21, 22, 23, 24, 25])

In [60]:
mat[4]

array([21, 22, 23, 24, 25])

根據以下輸出完成功能
```array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

18. 加總所有數據
325

In [62]:
mat.sum()

np.int64(325)

array([55, 60, 65, 70, 75])

In [63]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

Series
第一個我們將學習的主要數據類型是Pandas中的Series數據類型。讓我們導入Pandas並探索Series對象。

Series與NumPy陣列非常相似（事實上它是建立在NumPy陣列對象之上的）。將NumPy陣列與Series區分開來的是，Series可以具有軸標籤，這意味著它可以通過標籤進行索引，而不僅僅是通過數字位置。它也不需要保存數字數據，可以保存任意的Python對象。

讓我們通過一些示例來探索這個概念：

In [1]:
import numpy as np
import pandas as pd

In [2]:
myindex = ["USA","Canada","Mexico"]
mydata = [1776,1867,1821]

In [3]:
myser = pd.Series(data=mydata)

In [4]:
myser

0    1776
1    1867
2    1821
dtype: int64

In [5]:
pd.Series(data=mydata,index=myindex)

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [6]:
myser.index = myindex

In [7]:
myser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [8]:
ran_data = np.random.randint(0,100,4)

In [9]:
ran_data

array([60, 90, 75, 57], dtype=int32)

In [10]:
names = ["Ken","Vivin","Joy","Lucy"]

In [12]:
agres = pd.Series(ran_data,names)

In [13]:
agres

Ken      60
Vivin    90
Joy      75
Lucy     57
dtype: int32

In [14]:
agres = {"Sammy":5,"Frank":10,"Ken":7}
agres

{'Sammy': 5, 'Frank': 10, 'Ken': 7}

In [16]:
pd.Series(agres)

Sammy     5
Frank    10
Ken       7
dtype: int64

In [17]:
q1 = {'Japen':80,'China':450,'India':200,'USA':250}
q2 = {'Brazil':100,'China':500,'India':210,'USA':260}

In [18]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [19]:
print(type(sales_q1))

<class 'pandas.core.series.Series'>


In [20]:
sales_q1['Japen']

np.int64(80)

In [21]:
sales_q1[0]

C:\Users\s4292\AppData\Local\Temp\ipykernel_11920\92651501.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_q1[0]


np.int64(80)

In [22]:
sales_q1.iloc[0]

np.int64(80)

In [23]:
key = sales_q1.keys()

In [24]:
for k in key:
    if sales_q1[k] > 300:
        print(k,sales_q1[k])

China 450


In [25]:
sales_q1 * 2

Japen    160
China    900
India    400
USA      500
dtype: int64

In [26]:
sales_q1 / 100

Japen    0.8
China    4.5
India    2.0
USA      2.5
dtype: float64

In [27]:
sales_q1

Japen     80
China    450
India    200
USA      250
dtype: int64

In [28]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [29]:
sales_q1 + sales_q2

Brazil      NaN
China     950.0
India     410.0
Japen       NaN
USA       510.0
dtype: float64

In [30]:
sales_q1.add(sales_q2,fill_value=0)

Brazil    100.0
China     950.0
India     410.0
Japen      80.0
USA       510.0
dtype: float64

DataFrame

In [32]:
import numpy as np
import pandas as pd

In [ ]:
help(pd.DataFrame)

In [36]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

In [37]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)